### PR TITLE
fix: Graph package schema standardization

### LINKED ISSUE #969: Schema for graph api is completely wrong for structured properties.
## Version

looking at code, rc-latest

## Describe the bug

The .schema definitions for graph APIs does not match the property definition at all

## To Reproduce

Look at composer (Create event for instance)

You see this:

But the definition in the code is this:

This is a structured object. It's not a string, or number, or array or a boolean. 

This mismatch is because the .schema is completely wrong.

```
"eventToCreateProperty": {
      "$ref": "schema:#/definitions/valueExpression",
      "title": "New event",
      "description": "Event object to create.",
      "examples": []
    },
```

It's not a valueexpression.  A valueexpression says ANY object type is acceptable including value types.  This is not true.

The minimum schema should be declaring it's an `"schema:#/definitions/objectExpression",`

As that would tell the UI to at least put an object editor (json editor there.)

Better yet, tell us the shape of the object by providing a default object.  Here is a .schema for ConversationREference property:

```
  "conversationReference": {
          "$ref": "#/definitions/objectExpression",
          "title": "Conversation Reference",
          "description": "A conversation reference. (NOTE: Minimum required values or channelId, conversation).",
          "examples": [
            {
              "channelId": "skype",
              "serviceUrl": "http://smba.skype.com",
              "conversation": {
                "id": "11111"
              },
              "bot": {
                "id": "22222"
              },
              "user": {
                "id": "33333"
              },
              "locale": "en-us"
            }
          ]
        },
```

## Expected behavior

make it objectExpression with a examples:

### LINKED ISSUE #970: Properties in graph library are all named XXXXProperty.  That's not the SDK convention.
## Version

latest

## Describe the bug

Example:

```c#
        /// <summary>
        /// Gets or sets the timezone of the event.
        /// </summary>
        [JsonProperty("timeZoneProperty")]
        public StringExpression TimeZoneProperty { get; set; }

        /// <summary>
        /// Gets or sets the event and its property to update in graph.
        /// </summary>
        [JsonProperty("eventToCreateProperty")]
        public ObjectExpression<CalendarSkillEventModel> EventToCreateProperty { get; set; }
```

## To Reproduce

Look at code.

## Expected behavior

These should be named **timeZone** and **eventToCreate**

### PR DESCRIPTION
**Pull request by lauren-mills**
fixes #970 
fixes #969 

- Changed parameter names to remove "property"
- Set correct type values in schemas (rather than using valueExpression)
- Added oneOf property to drive better Composer UI
- Added items property on array types to drive composer UI
- changes dateTime properties to use StringExpression for correct UI 

NOTE: For the Attendee arrays, Composer does not provide adequate support for defining Arrays of Objects with multiple properties. I raised this issue in the Composer repo to track: https://github.com/microsoft/BotFramework-Composer/issues/7542

### CODE REVIEW

**Review by thomas-chung — DISMISSED** [review]
Thanks Lauren!

File: packages/Graph/GraphBotComponent.cs [hunk 1]
```diff
@@ -31,6 +36,12 @@ public override void ConfigureServices(IServiceCollection services, IConfigurati
                     services.AddSingleton<DeclarativeType>(sp => new DeclarativeType(attribute.DeclarativeType, type));
                 }
             }
+
+            services.AddSingleton<JsonConverterFactory, JsonConverterFactory<ObjectExpressionConverter<CalendarSkillEventModel>>>();
+            services.AddSingleton<JsonConverterFactory, JsonConverterFactory<ObjectExpressionConverter<OrdinalV2>>>();
+            services.AddSingleton<JsonConverterFactory, JsonConverterFactory<ObjectExpressionConverter<DateTime?>>>();
+            services.AddSingleton<JsonConverterFactory, JsonConverterFactory<ArrayExpressionConverter<Attendee>>>();
```
Comment (thomas-chung) [inline packages/Graph/GraphBotComponent.cs:43]: Should we pre-emptively add an object expression converter for Attendee as well?

File: packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.FilterEvents.schema [hunk 2]
```diff
@@ -24,47 +24,95 @@
...
+      "$ref": "schema:#/definitions/arrayExpression",
       "title": "Attendees",
       "description": "Attendees to filter by",
       "examples": [
-        "[\"janedoe@contoso.com\", \"johndoe@contoso.com\"]"
+        "=turn.attendeesParameter",
+        "[ 'Jane', 'John' ]"
+      ],
+      "default": [
+        "<name to filter by>"
```
Comment (thomas-chung) [inline packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.FilterEvents.schema:102]: Nit: should the example be an array of strings instead?

**Review by thomas-chung — APPROVED** [review]

File: packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.FilterEvents.schema (hunk 2 above)
Comment (lauren-mills) [reply packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.FilterEvents.schema:102]: You mean an array of empty strings? This will show up in the editor box so I wanted to try an make it obvious it needs to be changed

Comment (thomas-chung) [reply packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.FilterEvents.schema:102]: I was going to say sample names but whatever you have works still

File: packages/Graph/Schemas/Microsoft.Graph.Calendar.CreateEvent.schema [hunk 3]
```diff
@@ -26,25 +26,105 @@
...
       "title": "Token",
       "description": "Microsoft Graph API authentication token.",
       "examples": [
         "=turn.token.token"
       ]
     },
-    "eventToCreateProperty": {
-      "$ref": "schema:#/definitions/valueExpression",
+    "eventToCreate": {
+      "$ref": "schema:#/definitions/objectExpression",
```
Comment (tomlm) [inline packages/Graph/Schemas/Microsoft.Graph.Calendar.CreateEvent.schema:37]: >"$ref": "schema:#/definitions/objectExpression", [](http://example.com/codeflow?start=6&length=48)

I think the more correct description is to drop this.

**Review by tomlm — APPROVED** [review]
:shipit:

**Review by thomas-chung — APPROVED** [review]

File: packages/Graph/Schemas/Microsoft.Graph.Calendar.CreateEvent.schema (hunk 3 above)
Comment (lauren-mills) [reply packages/Graph/Schemas/Microsoft.Graph.Calendar.CreateEvent.schema]: Resolved
