### PR TITLE
[CalendarV2] fix bugs

### LINKED ISSUE #371: Test/Bug: Search for meeting at a certain time works well, maybe we can include if it's organized by yourself that we show - "you are the organizer"
Search for meeting at a certain time works well, maybe we can include if it's organized by yourself that we show - "you are the organizer"
image

### LINKED ISSUE #402: [Calendar Skill V2] suggested time could overly navigate
## Describe the bug

After clicking the > arrow, it could navigate to a bad page and meet errors:
image

### LINKED ISSUE #417: [Calendar Skill V2] internal exchange address is not properly displayed
## Describe the bug
If it is an exchange address, it is not properly displayed:
image

## To Reproduce
Create a contact that refers an internal user and then search

## Additional context
It seems it could be resolved like this https://social.msdn.microsoft.com/Forums/office/en-US/e78bd9ad-4ec3-4f2d-9939-747cafe77faa/how-to-resolve-the-email-address-in-this-form-oabcdouexchange-administrative-group

### PR DESCRIPTION
**Pull request by xhr0804**
### Purpose
*What is the context of this pull request? Why is it being done?*
close #417 
close #371
close #402 

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

### CODE REVIEW

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs [hunk 1]
```diff
@@ -2,6 +2,7 @@
 using System.Collections.Generic;
 using System.Linq;
 using System.Net.Http;
+using System.Text.RegularExpressions;
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs:5]: nit: if we order the using's alphabetically we can eliminate a lot of the compiler warnings + make the code easier to read.

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs [hunk 2]
```diff
@@ -63,23 +65,23 @@ public override async Task<DialogTurnResult> BeginDialogAsync(DialogContext dc,
             {
                 foreach (var contact in contacts)
                 {
-                    var emailAddresses = new List<string>();
-
-                    foreach (var email in contact.EmailAddresses)
+                    //var emailAddresses = new List<string>();
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs:68]: Dead code, probably can just go ahead and remove.

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs [hunk 3]
```diff
@@ -134,5 +136,11 @@ public override async Task<DialogTurnResult> BeginDialogAsync(DialogContext dc,
             // return the actionResult as the result of this operation
             return await dc.EndDialogAsync(result: results, cancellationToken: cancellationToken);
         }
+
+        private bool IsEmail(string emailString)
+        {
+            bool isEmail = !string.IsNullOrEmpty(emailString) && Regex.IsMatch(emailString, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase);
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs:142]: For perf gain you might want to also compile the regex as well.

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs [hunk 4]
```diff
@@ -63,23 +65,23 @@ public override async Task<DialogTurnResult> BeginDialogAsync(DialogContext dc,
             {
                 foreach (var contact in contacts)
                 {
-                    var emailAddresses = new List<string>();
-
-                    foreach (var email in contact.EmailAddresses)
+                    //var emailAddresses = new List<string>();
+                    var emailAddresses = contact.EmailAddresses.Where(e => !string.IsNullOrEmpty(e.Address) && IsEmail(e.Address)).Select(e => e.Address).ToList();
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs:69]: The IsNullOrEmpty is sort of redundant here because IsEmail already checks it.

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs [hunk 5]
```diff
@@ -102,7 +104,7 @@ public override async Task<DialogTurnResult> BeginDialogAsync(DialogContext dc,
                     foreach (var email in person.ScoredEmailAddresses)
                     {
                         // If the email address isn't already included in the contacts list, add it
-                        if (!contactsResult.SelectMany(c => c.EmailAddresses).Contains(email.Address))
+                        if (!contactsResult.SelectMany(c => c.EmailAddresses).Contains(email.Address) && IsEmail(email.Address))
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs:107]: This way of writing it is not optimal for large sets because we are asking the runtime to basically regenerate a stable list for every scored email address we have in the list which is an O(M*N) operation followed by another O(N) operation (the Contains()). 

I think we can make this code run faster, we can have a HashSet<T> of email addresses with the Contains() which turns it into an O(N) operation, then an O(1).

File: skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg [hunk 6]
```diff
@@ -259,7 +259,9 @@
     -
 
 # EventAttendeeContainer(event)
-- IF: ${ event.attendees != null && count(event.attendees) > 1 }
+- IF: ${ event.Response == 'organizer' }
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg:262]: New person question - can we just eliminate this if and instead have 

"IF ${event.Response != 'organizer' && event.attendees != null && count(event.attendees) > 1}"

Maybe it's clearer that way

File: skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg [hunk 7]
```diff
@@ -259,7 +259,9 @@
     -
 
 # EventAttendeeContainer(event)
-- IF: ${ event.attendees != null && count(event.attendees) > 1 }
+- IF: ${ event.Response == 'organizer' }  
+    -
+- ELSEIF: ${ event.attendees != null && count(event.attendees) > 1 }
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg:264]: Dumb question - is event.attendees > 1 because the organizer is always person 0?

File: skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog [hunk 8]
```diff
@@ -108,12 +108,18 @@
...
+            "id": "tdNJ28"
+          }
+        },
         {
           "$kind": "Microsoft.IfCondition",
           "$designer": {
             "id": "P1awzy"
           },
-          "condition": "(dialog.pageIndex * dialog.pageSize) - count(dialog.Items) <= dialog.pageSize",
+          "condition": "dialog.pageIndex * dialog.pageSize <  count(dialog.Items)",
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog:122]: I wonder if this equation is "too much math gymnasium" for non-technical customers to understand and whether or not we want to simplify this further. 

Basically what we are saying is "given the result set, what is the pages required to display all the information." then there is the question of "given where we are in the page index, are we at the end yet?" If we model it this way would it be easier to understand? And should we do it this way too?

File: skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog [hunk 9]
```diff
@@ -191,6 +205,14 @@
             }
           ],
           "elseActions": [
+            {
+              "$kind": "Microsoft.SetProperty",
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog:209]: I wonder if we should challenge this way to doing the flow design.

This makes complete sense to a programmer like us. But if we are shipping this to customers who are just dragging and dropping, then would they be overwhelmed and spend way too much time wondering why this is there in the first place?

Basically the way I think about this is - the dialog has a state - the current index, the number of pages required to display all the results. The various events/intents (still trying to use the right terms here) just trying to advance this count +1 and -1 until it hits either the beginning or end. Can we model it in such a way that the dialog's flow can demonstrate this?

Comment (thomas-chung) [reply skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog:209]: By the way, pagination is such an interesting reusable thing (I think). We may want to drill down on it some more.

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs (hunk 1 above)
Comment (lauren-mills) [reply skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs:5]: Yes, we need to add in the stylecop ruleset to these projects. I'll add that as a separate work item

File: skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog (hunk 8 above)
Comment (lauren-mills) [reply skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog:122]: @thomas-chung - why don't you take a look at the ListDialog separately and try to model it this way? It'd be a good exercise since that is one of the components we're hoping to ship as a separate reusable asset

File: skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg (hunk 6 above)
Comment (lauren-mills) [reply skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg:262]: I don't think this logic is quite right. If the user is the organizer, this will prevent it from showing any of the other attendees, when really we only want to hide the attendees if the user is the organizer and there are no other people coming to the meeting.

So the condition that checks for count(event.Attendees) == 1 should also include "&& event.Response != 'organizer"'.

**Review by lauren-mills — CHANGES_REQUESTED** [review]

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs (hunk 1 above)
Comment (thomas-chung) [reply skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs:5]: Actually our build already generates warnings for these types of issue. At least that's what I see when we are compiling main.

Comment (xhr0804) [reply skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs]: Fixed this line. I think there must be lots of style warning in this project. We can fix all at once later separately.

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs (hunk 3 above)
Comment (xhr0804) [reply skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs]: Added a RegexOptions.Compiled. Does that work?

File: skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg (hunk 6 above)
Comment (xhr0804) [reply skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg]: Actually, the previous logic is enough for most cases except a special one, that is the event.Attendees sometimes include the orgnizer him/herself and sometimes not include. So even if count(event.Attendees) ==1, we couldn't know whether the attendee is the orgnizer him/herself.

**Comment by xhr0804** [comment]
@lauren-mills Added a logic to filter the event.Attendees with the current user's Email. This will ensure the attendee list just contains other people and be empty if no other person.

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs (hunk 5 above)
Comment (xhr0804) [reply skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs]: good point, updated the code.

**Review by lauren-mills — APPROVED** [review]

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs [hunk 10]
```diff
@@ -134,5 +135,12 @@ public override async Task<DialogTurnResult> BeginDialogAsync(DialogContext dc,
             // return the actionResult as the result of this operation
             return await dc.EndDialogAsync(result: results, cancellationToken: cancellationToken);
         }
+
+        private bool IsEmail(string emailString)
+        {
+
```
Comment (thomas-chung) [inline skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs:141]: nit: extra line

**Review by thomas-chung — APPROVED** [review]
> Fixed this line. I think there must be lots of style warning in this project. We can fix all at once later separately. 

Yeah actually there are. I agree we can fix those later.

**Review by thomas-chung — APPROVED** [review]

File: skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs (hunk 10 above)
Comment (xhr0804) [reply skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs]: Oops..fixed
