### PR TITLE
fix: Update .NET Functions to use wwwroot dir for static files

### LINKED ISSUE #1112: Default static directory to wwwroot instead of www for .NET Functions-based bots
In response to https://github.com/microsoft/BotFramework-Composer/issues/7776, the decision was made in shiproom to update the static files root directory across the board to wwwroot. In response to this decision, the .NET Functions templates in the base adaptive generator need to be updated to use wwwroot instead of www.

### PR DESCRIPTION
**Pull request by peterinnesmsft**
### Purpose
Fixes #1112.

### Changes
- Update .NET Functions template files in @microsoft/generator-bot-adaptive to use wwwroot as the directory to serve static files from.
- Update JS SDK dependency version to 4.13.3-preview.

### Tests
N/A

### CODE REVIEW

**Review by ryanlengel — APPROVED** [review]

**Review by tracyboehrer — APPROVED** [review]

File: generators/generator-bot-adaptive/generators/app/index.js [hunk 1]
```diff
@@ -249,7 +249,7 @@ module.exports = class extends BaseGenerator {
   _writeJsPackageJson() {
     const { botName, integration } = this.options;
 
-    const sdkVersion = '~4.13.2-preview';
+    const sdkVersion = '~4.13.3-preview';
```
Comment (joshgummersall) [inline generators/generator-bot-adaptive/generators/app/index.js:252]: We may as well remove the tilde for now since it isn't buying us anything.

**Review by joshgummersall — APPROVED** [review]
One suggestion (stemming from annoyance with SDK semver and preview tag), otherwise looks good!

File: generators/generator-bot-adaptive/generators/app/index.js (hunk 1 above)
Comment (peterinnesmsft) [reply generators/generator-bot-adaptive/generators/app/index.js]: Fixed.

**Review by joshgummersall — APPROVED** [review]
